OSL-148: Adding Redis cache backend & caching shareableListPublic query
Pocket/shareable-lists-api pull request #120
Opened 2023-03-21 19:00 UTC by katerinachinnappan

## Goal

Adding Redis cache backend and caching response for `shareableListPublic` query. Previous PR had to be reverted, see [slack thread](https://pocket.slack.com/archives/C04HWMUKLN5/p1679368237398669). Removed `persistedQueries` from ApolloServer config as we only cache `shareableListPublic` query and that query is not big.

## Todos

- [ ] deploy to dev, ensure web-client works properly

## Tickets

- [https://getpocket.atlassian.net/browse/OSL-148](https://getpocket.atlassian.net/browse/OSL-148)

2023-03-21 22:34 UTC, jpetto requested changes
a few notes in code, but also:

i think we need to add tests around the cache. the result of caching _should_ be a `cache-control` header value sent in the response from calling the `shareableListPublic` query. our integration tests _do_ provide access to these headers, so theoretically we could verify that `cache-control` is set for `shareableListPublic` and _not_ set for all other queries. 

i don't know that we have prior art for this exact scenario. depending on my health levels tomorrow, we could pair or async investigate.

2023-03-22 02:47 UTC, katerinachinnappan commented on src/public/server.ts
> +      defaultMaxAge: config.app.defaultMaxAge,
@jpetto should we also default it to a minute then?

2023-03-22 05:59 UTC, katerinachinnappan commented on src/public/server.ts
> +      defaultMaxAge: config.app.defaultMaxAge,
@jpetto defaulted to 0 as we don't want to cache any other queries by default.

2023-03-22 15:37 UTC, jpetto requested changes
great job re-working this PR! a few small things to clean up, but the solution works!

i might also ask - just to be sure, could we add `cache-control` checks in the mutation integration tests as well?

2023-03-22 15:37 UTC, jpetto commented on schema-public.graphql
> +type ShareableListPublic implements ShareableListInterface
nicely done creating another type we can explicitly cache.

2023-03-22 15:37 UTC, jpetto commented on src/public/resolvers/queries/ShareableList.ts
> +  });
with the `@cacheControl` directives, i'm pretty sure we don't need to specify caching here as well. we should be able to remove this part.

2023-03-22 20:38 UTC, jpetto approved these changes
i think this is ready to go! give the team a heads up in the project channel before merge - but then send it.

great work!

2023-03-23 01:12 UTC, merged