chore(validation): [OSL-312] Remove emoji from list slugs
Pocket/shareable-lists-api pull request #124
Opened 2023-03-23 07:57 UTC by nina-py

## Goal

Improve slugs for shared lists.

- Updated `slugify` config to remove all characters that don't exist in the package's char map: https://github.com/simov/slugify/blob/master/config/charmap.json

- Added a neutral slug text for cases when list title is composed entirely of emoji or other characters that would be removed during the slugifying process: `shared-list`.

- Added two new integration tests to cover updated functionality.

## Tickets

https://getpocket.atlassian.net/browse/OSL-312

2023-03-23 15:36 UTC, jpetto requested changes
this is a great solution! i think we need one small change and one more test and it'll be good to go.

2023-03-23 22:46 UTC, nina-py commented on src/database/mutations/ShareableList.ts
> +      slugifiedTitle.length > 0 ? slugifiedTitle : 'shared-list';
Good catch, thank you, Jonathan!

2023-03-24 00:01 UTC, jpetto approved these changes
looks great! ship it!

2023-03-24 00:01 UTC, jpetto commented on src/database/mutations/ShareableList.ts
> +        slug: { contains: preparedSlug },
i know it's outside the scope of this PR, but i wonder if `startsWith` would be better here... definitely not a blocker.

2023-03-24 00:05 UTC, merged