OSL-371: Enfore itemId to be required at Prisma level
Pocket/shareable-lists-api pull request #140
Opened 2023-04-04 18:46 UTC by katerinachinnappan

## Goal

`itemId` field has been backfilled now, so the field can be enforced to be required on the Prisma level. Cleaned up some code for passing a null `itemId`.

## Tickets

- [https://getpocket.atlassian.net/browse/OSL-371](https://getpocket.atlassian.net/browse/OSL-371)

2023-04-04 18:58 UTC, Herraj reviewed
Wondering if we should add a unit test for the `parseFieldToInt` function?

2023-04-04 18:58 UTC, Herraj commented on src/database/mutations/ShareableListItem.ts
> +    itemId: parseInt(data.itemId),
I don't have context but is `itemId` defined as a `string` in gql schema?

2023-04-04 18:58 UTC, Herraj commented on src/shared/resolvers/fields/PrismaBigInt.ts
> +  return isNaN(parsedField) ? null : parsedField;
Would be nice to add a return type of `number | null` to the function and update the function comment!

2023-04-04 19:00 UTC, katerinachinnappan commented on src/database/mutations/ShareableListItem.ts
> +    itemId: parseInt(data.itemId),
@Herraj its `ID` type which is interpreted as a string I believe, but we store it as a BigInt in the db

2023-04-04 20:24 UTC, jpetto requested changes
one change request on the field resolver, and i think we should update [this helper](https://github.com/Pocket/shareable-lists-api/blob/main/src/public/resolvers/utils.ts#L84) to not allow a missing/empty `itemId`.

2023-04-04 20:24 UTC, jpetto commented on src/shared/resolvers/fields/PrismaBigInt.ts
> +  return isNaN(parsedField) ? null : parsedField;
clarification: if `isNaN(parsedField)` is true, that means we have a value in the database that cannot be parsed into a number, right? if so, that would be a big problem 😅. 

in other words, this function should _never_ return anything _except_ a `number`, right?

2023-04-04 20:31 UTC, Herraj commented on src/shared/resolvers/fields/sharedResolversFields.spec.ts
> +      expect(resolvedValue).to.be.null;
We should also assert the sentry stub to be called once in this test case

2023-04-04 20:31 UTC, Herraj commented on src/shared/resolvers/fields/sharedResolversFields.spec.ts
> +      expect(resolvedValue).to.equal(parseInt(itemId));
This is ok and works but to have a more "truer" test, we should replace the `equal(parseInt(item))` with `equal(12345)`

The reason I say this is because we want to treat our function call, `parseFieldToInt` as a black box. So whatever value it returns we assert it against what we expect. What you have now (`parseInt(itemId)`) is basically mimicking the inner workings of that function, which kind of defeats the purpose of testing. If for some reason our function logic was incorrect we'd never catch the bug in our test.

Does that make sense? 😄 once again I think it's fine in this situation since it's a very simple function and we can eyeball what `parseInt("12345")` would return.

2023-04-04 21:52 UTC, katerinachinnappan commented on src/shared/resolvers/fields/PrismaBigInt.ts
> +  return isNaN(parsedField) ? null : parsedField;
@jpetto that is right, if `validateItemId` function is already validating the value prior to inserting it into the db, then we don't need the validation in the resolver function. It can simple return `parseInt(value)` and we don' need to log anything into Sentry then.

2023-04-04 21:57 UTC, jpetto commented on src/shared/resolvers/fields/PrismaBigInt.ts
> +  return isNaN(parsedField) ? null : parsedField;
i think it's a good idea to keep a check that `parseInt(field)` gives us a number, and a Sentry call if not. it would be an extra layer of protection/notice if somehow the input validation began failing.

2023-04-04 22:16 UTC, Herraj approved these changes

2023-04-06 16:41 UTC, jpetto requested changes
one small ask on a test, but then good to go!

2023-04-06 16:41 UTC, jpetto commented on src/shared/resolvers/fields/PrismaBigInt.ts
> +  return parsedField;
not a blocker, but in the future could consider consolidating the `parseInt(field)` call into a variable 😄

2023-04-06 16:41 UTC, jpetto commented on src/shared/resolvers/fields/sharedResolversFields.spec.ts
> +      const itemId = '12345';
won't the actual value from the database be like `12345n`? if so, can we update the test to validate?

2023-04-06 18:58 UTC, jpetto approved these changes
lgtm! be sure to deploy to dev first (if you haven't already 😄)

2023-04-06 18:59 UTC, merged