OSL-386: Execute data deletion from /deleteUserData express endpoint
Pocket/shareable-lists-api pull request #148
Opened 2023-04-12 18:41 UTC by katerinachinnappan

## Goal

Legal said we don't need to retain any data. When a user deletes their account, `/deleteUserData` endpoint will delete all shareable list data from the db for that user. Added integration test for `/deleteUserData` endpoint.

## Tickets

- [https://getpocket.atlassian.net/browse/OSL-386](https://getpocket.atlassian.net/browse/OSL-386)

2023-04-12 19:26 UTC, jpetto requested changes
the approach is good - just some comments and suggestions around tightening things up.

2023-04-12 19:26 UTC, jpetto commented on src/public/routes/deleteUserData.ts
> +    shareableListIds.push(parseInt(list.id as unknown as string));
nit - could we put a comment on this line as to why we have to double cast?

2023-04-12 19:26 UTC, jpetto commented on src/public/routes/deleteUserData.ts
> +  } else if (shareableListIds.length > 0) {
nit - you could drop the `else` here, as when the `if` is truthy, the function returns.

2023-04-12 20:07 UTC, katerinachinnappan commented on src/public/routes/deleteUserData.ts
>      const requestId = req.body.traceId ?? nanoid();
@jpetto I am actually not sure, this seems to be the pattern in other repos and I have assumed this is part of the POST request lambda sends to the endpoint, to trace the request.

2023-04-12 23:15 UTC, jpetto commented on src/public/routes/deleteUserData.ts
>      const requestId = req.body.traceId ?? nanoid();
hmm, okay. after some looking, i _think_ this pattern came from kat with the intent of tracing a request through the apollo gateway down to the specific subgraph (to match errors in the gateway to errors in the subgraph). as in this case we are going directly from a lambda to this service, i don't think we need to add this `requestId`. if that sounds right to you, i say we remove it to keep the code clean.

but - let me know if you do see a use case!

2023-04-12 23:16 UTC, jpetto requested changes
thanks for addressing all the feedback! looks great. one last thing to remove the `requestId`, then i think we'll be good.

2023-04-13 17:38 UTC, katerinachinnappan commented on src/public/routes/deleteUserData.ts
>      const requestId = req.body.traceId ?? nanoid();
@jpetto if this is the case, then lets discard it!

2023-04-13 18:02 UTC, jpetto approved these changes
nice work! thanks for all the changes on this one!

2023-04-13 18:09 UTC, merged