feat(updateShareableListItem): add mutation and tests
Pocket/shareable-lists-api pull request #155
Opened 2023-04-19 18:44 UTC by jpetto

## Goal

add `updateShareableListItem` mutation w/tests.

## Tickets

- https://getpocket.atlassian.net/browse/OSL-393

2023-04-26 20:06 UTC, katerinachinnappan requested changes

2023-04-26 20:06 UTC, katerinachinnappan commented on schema-public.graphql
> +  updateShareableListItem(
PR looks good to me but wondering if we should wait for bulk add work and also update this mutation to accept array

2023-05-01 19:00 UTC, jpetto commented on src/database/mutations/ShareableListItem.ts
> +    throw new NotFoundError(`A list item by that ID could not be found`);
404 is the safer option, as it doesn't reveal any information about information owned by other users. 403 would let an attacker know that whatever data they have stumbled upon is in fact real data.

2023-05-01 19:01 UTC, jpetto commented on schema-public.graphql
> +  updateShareableListItem(
decided in our review meeting that we can ship this now to unblock notes and we'll revisit the bulk update stuff in a later ticket.

2023-05-01 19:07 UTC, katerinachinnappan approved these changes

2023-05-01 19:45 UTC, merged