OSL-478: Adding updateShareableListItems mutation for bulk edit feat
Pocket/shareable-lists-api pull request #191
Opened 2023-05-03 22:08 UTC by katerinachinnappan

## Goal

Adding a new `updateShareableListItems` mutation which accepts an array of shareable list item `sortOrder`. This is for bulk edit/ reorder effort.

## Tickets

- [https://getpocket.atlassian.net/browse/OSL-478](https://getpocket.atlassian.net/browse/OSL-478)

## Implementation Decisions

According to this [known issue](https://github.com/prisma/prisma/issues/6862), it is not possible to use the `updateMany` prisma call to update several rows with different values, so using the [transactions API ](https://www.prisma.io/docs/guides/performance-and-optimization/prisma-client-transactions-guide#transaction-api)to perform the bulk update.

2023-05-03 23:45 UTC, kschelonka commented on schema-public.graphql
> +    data: [UpdateShareableListItemsInput!]!
I'd advocate a limit here so that no one can take down the db with a massive transaction can use `@constraint(minItems: 1, maxItems: XX)`

2023-05-04 14:44 UTC, jpetto requested changes
this is great work. agree we need a max limit, and one request for an additional test (only bc transactions are a preview feature).

2023-05-04 14:44 UTC, jpetto commented on schema-public.graphql
> +    data: [UpdateShareableListItemsInput!]!
agree with @kschelonka here - we need to have some kind of limit to protect ourselves. i brought this up recently (when? where? idk 🙃 ), but @anthony-liddle mentioned the web team already limits these calls in batches of 30, which i think is a very reasonable limit. i'd be fine starting with a max of 30 and increasing from there if/when the need arises.

2023-05-04 14:44 UTC, jpetto commented on src/public/resolvers/mutations/ShareableListItem.integration.ts
> +      );
i generally do not advocate to test the behavior of a library, BUT since transactions are a preview feature, i think it would be nice (and make me feel more confident) if we added a check in this test that the valid list items have _not_ been updated. (could just do a direct prisma query and validate the returned data.) too many years in software has made me suspicious 😅

2023-05-04 19:48 UTC, jpetto approved these changes
nice! ship it!

2023-05-04 19:53 UTC, merged