OSL-499: Metadata refactoring - extend Parser Item type in the shareable lists API
Pocket/shareable-lists-api pull request #209
Opened 2023-05-18 17:44 UTC by katerinachinnappan

## Goal

* Extending the Parser `Item` type
* Adding a `dataLoader` for `ShareableListItem`
* Adding & testing `__resolveReference` for `ShareableListItem`

## Todos

- [ ] test in dev
- [ ] make changes in `parser-graphql-wrapper`

## Tickets

- [https://getpocket.atlassian.net/browse/OSL-499](https://getpocket.atlassian.net/browse/OSL-499)

2023-05-18 19:25 UTC, jpetto requested changes
a few small questions/suggestions as-is, but the big piece piece missing is limiting results based on `userId`. at this point, the use case is solely to tie saves to shareable list items, meaning the results need to be filtered by the current user.

i think we can do as you suggested and pull the `userId` from the headers as we do for other queries. the tricky part/big question is - will headers be sent down to other subgraphs/subgraph queries? or will headers get "trapped" in the originating subgraph (parser-graphql-wrapper, in this case)? if this _doesn't_ work, we might need to ticket a blocking ticket to figure out that flow.

2023-05-18 19:25 UTC, jpetto commented on src/dataLoaders/shareableListItemLoader.ts
> +    if (listItem) {
do we need this check? could a `listItem` in this iterator ever be falsy?

2023-05-18 19:53 UTC, katerinachinnappan commented
@jpetto correct me if I am wrong but does list api get the userId for saves from the headers as well -- passed via`parser-graphql-wrapper` subgraph?

2023-05-18 20:45 UTC, katerinachinnappan commented
@jpetto i think we might need to do something like this?

https://github.com/Pocket/list-api/blob/main/schema.graphql#L558

2023-05-18 21:46 UTC, jpetto commented
> @jpetto i think we might need to do something like this?
> 
> https://github.com/Pocket/list-api/blob/main/schema.graphql#L558

yes. and, what do you mean? 😆

the yes is - using that example for our case, `User` would be `Item`, and `SavedItems` would be `ShareableListItems`. i poked into the resolvers in that repo, and see that it _is_ getting `userId` from the context - which means we can hopefully do the same.

2023-05-18 21:53 UTC, kschelonka commented on src/public/resolvers/index.ts
> +    __resolveReference: resolveShareableListItemParserItemReference,
I don't think you need this, unless I'm mistaken about what exists in other subgraphs. can other subgraphs send representations of a shareable list item?

2023-05-18 21:56 UTC, kschelonka commented on src/public/resolvers/item.ts
> +    throw err;
You're double-reporting here, can remove this since you use the Sentry plugin.

2023-05-19 15:51 UTC, jpetto commented on src/public/resolvers/index.ts
> +    __resolveReference: resolveShareableListItemParserItemReference,
@kschelonka the use case is - when clients request an `Item` as a subquery of a `SavedItem`, they want to see what shareable lists that `Item` may be a part of. so, i think we do need this?

2023-05-22 15:54 UTC, jpetto requested changes
re-read / re-thought kat's comment and saw her point - we should be able to drop the `__referenceResolver` here.

2023-05-22 15:54 UTC, jpetto commented on src/public/resolvers/index.ts
> +    __resolveReference: resolveShareableListItemParserItemReference,
actually wait - i think kat is right 😅. the `Item: { shareableListItem }` resolver above handles all current use-cases. (e.g. all these tests pass if you remove the `__resolveReference` line.)

the difference between this subgraph and collections (which i believe this PR was modeled on) is that the parser-graphql-wrapper extends the `Collection` type with additional fields, which (i think?) is what necesitates a `__referenceResolver` in collection-api.

we should be able to remove this resolver.

2023-05-22 16:43 UTC, katerinachinnappan commented on src/public/resolvers/index.ts
> +    __resolveReference: resolveShareableListItemParserItemReference,
Ahh yes that makes sense. Parser-graphql-wrapper will not add any additional properties to the shareable list item type

2023-05-22 21:10 UTC, jpetto commented on src/public/resolvers/index.ts
> +    __resolveReference: resolveShareableListItemParserItemReference,
now that we've switched to `SavedItem`, i think we'll still have to define that as a property in list API, which will require a `type ShareableListItem` in the schema. but it'll just be a reference (like we have for `Item` in this repo).

2023-05-22 21:20 UTC, katerinachinnappan commented on src/public/resolvers/index.ts
> +    __resolveReference: resolveShareableListItemParserItemReference,
yep, I have a PR coming up in a lil bit

2023-05-22 21:47 UTC, katerinachinnappan commented on src/public/resolvers/index.ts
> +    __resolveReference: resolveShareableListItemParserItemReference,
@jpetto I'm re-reading apollo docs and not following anymore why we still need to reference shareable list item in list API? we have already extended `SavedItem` in this repo and added an additional `shareableListItem` property which we also resolve in this repo. 

So a user can check if a save item is also a shareable list item by drilling into the user -> save item -> shareable list item.

What do we achieve with referencing `ShareableListItem` type in list API? we aren't adding any additional properties to `ShareableListItem` type in List API.

2023-05-22 22:09 UTC, jpetto commented on src/public/resolvers/index.ts
> +    __resolveReference: resolveShareableListItemParserItemReference,
you're totally right 😄. the graph does it for us since we're `extend`ing the type.

2023-05-22 22:10 UTC, jpetto approved these changes
this is looking good! i think we can merge and wait for the web team to test some queries.

2023-05-22 22:17 UTC, merged