feat(batchDelete): update endpoint to queue list items for batch delete
Pocket/shareable-lists-api pull request #246
Opened 2023-06-20 23:34 UTC by jpetto

- use @pocket-tools ts config

## Goal

Insert purpose of pull request

## Todos

- [ ] Outstanding todo
- [x] Completed todo

## Modifying Environment Variables

Omit this section if not applicable.

- [ ] Variables added to SSM
- [ ] Variables added to terraform environment config

Have you followed the guidelines in our Contributing document?

## Deployment

- [ ] Secrets?

## Reference

Documentation here:

- Link to docs

## Tickets

- Link to JIRA tickets

## Implementation Decisions

2023-06-21 18:36 UTC, katerinachinnappan requested changes

2023-06-21 18:36 UTC, katerinachinnappan commented on src/config/index.ts
> +        ? process.env.AWS_ENDPOINT || 'http://localstack:4566'
should the port be `4567` and expose it in docker-compose as well? I think S3 endpoint is pointing to `4566`

2023-06-21 18:36 UTC, katerinachinnappan commented on src/config/index.ts
> +          'http://localhost:4566/queue/ShareableListsApi-Local-Batch-Delete-Consumer-Queue',
I think port should be `4567`?

2023-06-21 18:36 UTC, katerinachinnappan commented on src/config/index.ts
> +    externalIdChunkSize: 25,
so did we decide the limit is 25 items to delete?

2023-06-21 18:36 UTC, katerinachinnappan commented on src/express.ts
> +import deleteShareableListItemsRouter from './public/routes/queueDeleteShareableListItems';
nit pick - just for consistency should we rename this to `queueDeleteShareableListItemsRouter`

2023-06-21 18:36 UTC, katerinachinnappan commented on src/public/routes/queueDeleteShareableListItems.ts
> +export type DeleteListItemsSqsMessage = {
again just a nit pick  -  rename for consistency to `QueueDeleteShareableListItemsSQSMessage`

2023-06-21 18:36 UTC, katerinachinnappan commented on src/public/routes/queueDeleteShareableListItems.ts
> +const deleteShareableListItemDataSchema: Schema = {
suggestion to rename to `queueDeleteShareableListItemDataSchema`

2023-06-22 15:05 UTC, jpetto commented on src/config/index.ts
> +        ? process.env.AWS_ENDPOINT || 'http://localstack:4566'
i think this is our first usage of an AWS endpoint in code? if so, it should be fine as-is. (also pretty sure localstack exposes _all_ services on port `4566` now.)

2023-06-22 16:44 UTC, jpetto commented on docker-compose.yml
> -      - SERVICES=s3
services aren't required to be defined in localstack 2.1 😄 - they are spun up on demand.

2023-06-22 16:51 UTC, katerinachinnappan approved these changes
🚀

2023-06-22 16:55 UTC, merged