feat(query): OSL-146 Add `shareableList` query
Pocket/shareable-lists-api pull request #27
Opened 2023-02-10 09:50 UTC by nina-py

## Goal

- Updated the public schema to remove fields that shouldn't be exposed on the public graph

- Added resolvers for `shareableList` query and return types.

## Todos

- [ ] Get feedback on the schema changes
- [ ] Get feedback on the shape of the proposed query (with two variables) is what we need
- [ ] Add helper functions for `List` and `ListItems` for generating data for integration tests
- [ ] Add integration tests

## Tickets

-  https://getpocket.atlassian.net/browse/OSL-146

2023-02-10 09:54 UTC, nina-py commented on schema-public.graphql
>  }
Does this look about right? Should we be batching up variables in some sort of `Input` type, or is this okay as is given there are only two variables?

2023-02-10 16:04 UTC, katerinachinnappan commented on schema-public.graphql
> +scalar ISOString
Yeah I think this is a newer version so lets stick to this!

2023-02-10 16:04 UTC, katerinachinnappan commented on schema-public.graphql
>  }
Good catch!

2023-02-10 16:05 UTC, katerinachinnappan commented on schema-public.graphql
>  }
This is ok! I did the same with `Labels` in collection-api.

2023-02-10 16:13 UTC, jpetto requested changes
i think only one bug (omitting `sortOrder` from the db type), and a suggestion to maybe include the created/updated at fields for list items.

love this quick turnaround clean up!

2023-02-10 16:13 UTC, jpetto commented on schema-public.graphql
> +scalar ISOString
i think we should continue using this format. 👍

2023-02-10 16:13 UTC, jpetto commented on schema-public.graphql
>  }
great catch!

2023-02-10 16:13 UTC, jpetto commented on schema-public.graphql
> +  updatedAt: ISOString!
no worries nina - this is why we iterate 😄

2023-02-10 16:13 UTC, jpetto commented on src/database/types.ts
> +  | 'updatedAt'
any reason we shouldn't send `sortOrder`, `createdAt`, and `updatedAt`? looks like we're retrieving `sortOrder` in the query resolver above, and created/updated might be nice metadata for clients (that they can of course omit).

2023-02-10 16:13 UTC, jpetto commented on schema-public.graphql
>  	sortOrder: Int!
any reason we shouldn't include `createdAt` and `updatedAt` as available fields here?

2023-02-10 16:17 UTC, katerinachinnappan commented on src/public/index.ts
> +export const index = {
not blocking but we could probably leave this as `resolvers` to be more intuitive. same with the file name change

2023-02-10 16:18 UTC, katerinachinnappan commented on src/public/resolvers/queries/ShareableList.ts
> +  const list = await dbGetShareableList(db, userId, slug);
are we getting the  `userId` from the headers?

2023-02-10 16:21 UTC, jpetto commented on schema-public.graphql
>  }
i think this is okay for the use cases we can see. getting a single entity _shouldn't_ have many filter options.

2023-02-10 16:22 UTC, jpetto commented on src/public/resolvers/queries/ShareableList.ts
> +  const list = await dbGetShareableList(db, userId, slug);
good catch @katerinachinnappan! we likely need a context manager here to pull the header value out.

2023-02-10 18:47 UTC, katerinachinnappan commented on src/public/resolvers/queries/ShareableList.ts
> +  const list = await dbGetShareableList(db, userId, slug);
@jpetto yep, I have that in my PR for creating a list!

2023-02-13 10:12 UTC, nina-py commented on src/database/types.ts
> +  | 'updatedAt'
Good point - added those

2023-02-13 10:15 UTC, nina-py commented on src/public/index.ts
> +export const index = {
Good catch, this was meant to go in the `/resolvers/` folder hence the renaming to `index.ts`. The IDE updated the variable name for me and I didn't notice.

2023-02-14 04:00 UTC, nina-py commented on schema-public.graphql
>  	sortOrder: Int!
Added them in!

2023-02-14 04:12 UTC, nina-py commented on src/public/context.ts
> +    }
I have moved this from the mutation to the context as we need this check everywhere

2023-02-14 04:12 UTC, nina-py commented on src/public/resolvers/mutations/ShareableList.integration.ts
> +      });
I updated integration tests for the mutation as they needed changes following a refactor of the helpers.

2023-02-14 04:12 UTC, nina-py commented on src/test/helpers/createShareableListHelper.ts
> +): Promise<List> {
Updated this to return Prisma types rather than types that match the public schema - this way the returned object can be used in more flexible ways (e.g., for admin graph integration tests, too), and also has props we need to link list items to lists.

2023-02-14 20:08 UTC, jpetto requested changes
this looks really good - i think the only required update is changing from `slug` to `externalId` as the lookup param.

2023-02-14 20:08 UTC, jpetto commented on schema-public.graphql
> +  shareableList(slug: String!): ShareableList
for this auth-only query, we'll use `externalId` instead of `slug`. apologies that this wasn't made clear in the ticket. 😞

2023-02-14 20:08 UTC, jpetto commented on src/config/index.ts
> +  slugify: { lower: true, remove: /[*+~.()'"!:@]/g },
nice

2023-02-14 20:08 UTC, jpetto commented on src/public/context.ts
> +    }
there's _one_ place we won't need this, and that's on the `publicShareableList` query.

2023-02-14 20:08 UTC, jpetto commented on src/test/helpers/createShareableListItemHelper.ts
> +    sortOrder: data.sortOrder ?? faker.datatype.number(),
no changes needed, but just calling out that `listId`, `url`, and `sortOrder` are the only guaranteed fields (ty parser).

2023-02-14 21:04 UTC, nina-py commented on schema-public.graphql
> +  shareableList(slug: String!): ShareableList
Fixed!

2023-02-14 21:05 UTC, jpetto approved these changes
looks good!

2023-02-14 21:09 UTC, merged