OSL-95: adding createShareableList mutation
Pocket/shareable-lists-api pull request #28
Opened 2023-02-10 16:08 UTC by katerinachinnappan

## Goal

* Adding a `createShareableList` mutation
* Adding integration test
* Updating public schema and db types per @nina-py suggestion in her PR
* Updating prisma schema and making `slug` optional on `List` type (we don't provide the `slug` when creating a List)

## Todos

- [ ] deploy to dev
- [x] Fix CircleCI test_integration error

## Tickets

- [https://getpocket.atlassian.net/browse/OSL-95](https://getpocket.atlassian.net/browse/OSL-95)

2023-02-10 20:25 UTC, katerinachinnappan commented on schema-public.graphql
> +"""
Pulling in @nina-py proposed schema changes

2023-02-10 20:26 UTC, katerinachinnappan commented on src/public/context.ts
> +  get userId(): string {
I think this is the way the `userId` will be passed to in the headers?

2023-02-10 22:27 UTC, kschelonka commented on .circleci/config.yml
> +          command: npm install
👍

2023-02-10 22:30 UTC, kschelonka commented on schema-public.graphql
> +"""
fyi - @hyperparabolic and @cmharlow plan to work on functions for de/serializing and include in apollo-utils

2023-02-10 22:34 UTC, kschelonka commented on src/public/context.ts
> +  get userId(): string {
You probably don't need to use this `get` pattern now that we're on apollo v4 and it's easy to pass request headers. I used this so that it was possible to mock the response from the context for some integration tests.

2023-02-10 22:38 UTC, kschelonka commented on src/public/resolvers/mutations/ShareableList.ts
> +  if (!userId) {
I recommend moving this to the context or a specific model, so that you have finer control over your business logic over the domain (vs. re-exporting and wrapping all mutations).

2023-02-10 22:42 UTC, kschelonka commented on src/public/resolvers/mutations/ShareableList.ts
> +export async function createShareableList(
Recommend consolidating over domain vs. operation -- so rather than a file with all mutations as a namespace, consider creating model for ShareableList entity and put the creation logic there (along with retrieval logic).

2023-02-10 23:05 UTC, jpetto requested changes
this is a great start on a sizeable PR 😄. a few requests, but nothing too big.

2023-02-10 23:05 UTC, jpetto commented on src/public/resolvers/mutations/ShareableList.ts
> +  if (!userId) {
i don't know if context will work, as this user check doesn't apply to every operation. all queries except one (for now) need this check, and all mutations need it. but agree this would be better moved to the model resolver layer.

(this pattern for mutations from collections is kind of a one-off that we haven't carried forward anywhere else. (we should probably standardize collections api.))

2023-02-10 23:05 UTC, jpetto commented on src/public/resolvers/mutations/ShareableList.ts
> +export async function createShareableList(
yep, agree with kat. [curated-corpus-api](https://github.com/Pocket/curated-corpus-api/tree/main/src/admin/resolvers) has some nice structure in this regard.

2023-02-11 03:05 UTC, katerinachinnappan commented on src/public/resolvers/mutations/ShareableList.ts
> +export async function createShareableList(
not sure if I am following. What is the reason and what are the drawbacks of the current structure? @jpetto

2023-02-11 03:43 UTC, katerinachinnappan commented on .circleci/scripts/setup.sh
> +chmod +x "./"
@jpetto unfortunately doesn't work without `chmod +x`. circleci complains about the scripts not being executable & then also about permissions on top of that. you can check some previous failed runs on this. 😢

2023-02-11 03:44 UTC, katerinachinnappan commented on .circleci/config.yml
> +          command: npm install
switched back to `ci` according to the slack thread on this. also removed caching step

2023-02-13 16:57 UTC, jpetto requested changes
hopefully cleared up some confusion i was a part of adding last week.

also remembered a slug will not be present at creation time, so we can drop all that input/logic 😄

2023-02-13 16:57 UTC, jpetto commented on schema-public.graphql
> +	slug: String!
a weekend of rest gives a clear mind - we won't get a slug when a list is created. slugs only need to be generated once the list is published, so we can drop this from the input 😄

(part of this is because, for MVP, slugs are immutable once generated, and will be based off the title. a user can edit a title as often as they want - so we want to delay creating the slug until we need it.)

2023-02-13 16:57 UTC, jpetto commented on src/public/context.ts
> +    return userId instanceof Array ? userId[0] : userId;
is this sometimes an array?

2023-02-13 16:57 UTC, jpetto commented on src/public/resolvers/mutations/ShareableList.ts
> +export async function createShareableList(
apologies for the ambiguity! i think i read @kat's suggestion wrong (but would be interested to hear more detail there).

my suggestion for this PR (and we may iterate on this pattern as we add more mutations), is to simply move the `userId` check (back?) into the `executeMutation` function. we know all mutations will require this check, so i think it's safe to perform this abstraction at this stage, and better to put here than in the database-specific function.

2023-02-13 18:22 UTC, katerinachinnappan commented on src/public/context.ts
> +    return userId instanceof Array ? userId[0] : userId;
@jpetto I believe `request.headers.userid` is actually an array.

2023-02-13 20:55 UTC, jpetto approved these changes
a couple small things that can be addressed in a follow up. (please make a ticket so we don't forget!) nice work on this big PR!

2023-02-13 20:55 UTC, jpetto commented on src/database/types.ts
> +  | 'updatedAt'
noting that @nina-py's PR has some changes here - but we can resolve those in her PR.

2023-02-13 20:55 UTC, jpetto commented on src/public/resolvers/mutations/ShareableList.integration.ts
> +      expect(result.body.errors.length).to.equal(1);
for a later PR - would be good to `expect` the error code (whatever `UserInputError` throws) here. it's a little more concrete/pertinent than the error message.

2023-02-13 20:55 UTC, jpetto commented on src/public/resolvers/mutations/ShareableList.integration.ts
> +      // create new List with title1 value for the same user
nit pick (non blocker): looks like a copy pasta comment that isn't accurate for this test 😄

2023-02-13 20:55 UTC, jpetto commented on src/public/resolvers/mutations/ShareableList.ts
> +  }
one more thing for a follow-up PR: an integration test file (we've used the pattern of `ShareableList.auth.integration.ts`) where we validate the error thrown here.

2023-02-13 20:59 UTC, merged

2023-02-13 21:01 UTC, efixler commented on .circleci/scripts/setup.sh
> +chmod +x "./"
@katerinachinnappan Have you tried `git update-index`? I know this is only supposed to be required when traversing windows file systems, but I have in the past had success using it to fix this issue where git doesn't persist file executable bits properly.