feat(mutation): [OSL-103] Ad`d addShareableListIt`em mutation w/ tes
Pocket/shareable-lists-api pull request #41
Opened 2023-02-16 08:18 UTC by nina-py

## Goal

Allow users to add stories (items) to their lists.

- [x] Added a new mutation and all checks 

- [ ] Added tests

## Tickets

- https://getpocket.atlassian.net/browse/OSL-103

2023-02-17 10:41 UTC, nina-py commented on schema-public.graphql
> +	url: Url!
I've updated this type to add `externalId` which is an input for the `deleteShareableListItem` mutation, and I've also made `url` required/guaranteed as these are also unique identifiers and we compare them against other stories in the same list to see if there are any duplicates.

2023-02-21 05:26 UTC, katerinachinnappan commented on src/public/resolvers/mutations/ShareableListItem.integration.ts
> +        .send({
seems like the header is missing from the request?

2023-02-21 05:27 UTC, katerinachinnappan commented on src/public/resolvers/mutations/ShareableListItem.integration.ts
> +        'FORBIDDEN'
should we be testing for a `bad user input` error code instead? Seems like the `forbidden` code is thrown because the headers are missing from the request?

2023-02-21 05:28 UTC, katerinachinnappan commented on src/public/resolvers/mutations/ShareableListItem.integration.ts
> +        .send({
headers missing in request?

2023-02-21 05:29 UTC, katerinachinnappan commented on src/public/resolvers/mutations/ShareableListItem.integration.ts
> +  describe('createShareableListItem', () => {
should we also add a test case for a user trying to add a list item to another user's list? The UI will probably not allow it but worth to check here?

2023-02-21 05:30 UTC, katerinachinnappan requested changes
Looks great, just some minor comments about testing!

2023-02-22 02:18 UTC, nina-py commented on src/public/resolvers/mutations/ShareableListItem.integration.ts
> +        .send({
Well-spotted, thank you @katerinachinnappan !

2023-02-22 02:18 UTC, nina-py commented on src/public/resolvers/mutations/ShareableListItem.integration.ts
> +        'FORBIDDEN'
Fixed!

2023-02-22 04:14 UTC, katerinachinnappan approved these changes
⭐ 🔥

2023-02-22 04:15 UTC, merged