Osl 147 public query
Pocket/shareable-lists-api pull request #54
Opened 2023-02-22 09:55 UTC by nina-py

## Goal

Provide a query to retrieve a list that has been shared publicly.

## Todos

- [x] Scaffold the basics
- [ ] Work out implementation details
- [ ] Add tests

## Tickets

https://getpocket.atlassian.net/browse/OSL-147

2023-02-22 16:43 UTC, efixler commented on schema-public.graphql
> +  publicShareableList(slug: String!, userId: Float!): ShareableList
Couple things come to mind here: 

- Naming: Why not just something like `list` or `getList`? It feels like internally we are very wrapped around the concepts of "public" and "shareable" but these don't feel like concepts that are really meaningful outside the technical conversations (also, collections are both public and shareable, so I don't see how these adjectives meaningfully differ) 

- Is the userId here the user we are working on-behalf-of, or is it the creator of the list? I think the answer to the question of whether to use the headers or not is based on that -- the headers should only be used for, and are considered trusted for, the on-behalf-of user (right?). 

- (slugs do not appear to have a unique constraint which implies that the userId here is the list creator because we need that double for lookup)

2023-02-22 16:46 UTC, efixler commented on src/database/queries/ShareableList.ts
> +  const storedSlug = matches[0];
I agree that this seems clunky. Why don't we store the entire slug in the DB?

Also, slightly OT, but does our slug generator handle accented/UTF-8 characters robustly?

(also, I always love a good use of non-greedy regex pattern matching :) )

2023-02-22 19:07 UTC, katerinachinnappan commented on schema-public.graphql
> +  publicShareableList(slug: String!, userId: Float!): ShareableList
I think the naming here is fine, `public` because a list can be `private` or `public` and `shareable`, well, because these lists have the capability to be shared outside of pocket. And I don't think we can actually share collections atm? 

About the `userId` being part of the query parms, I think that is correct. We already have a `getShareableList` which requires authentication and it is for both private & public lists.

2023-02-22 21:31 UTC, kschelonka commented on schema-public.graphql
> +  publicShareableList(slug: String!, userId: Float!): ShareableList
> Naming: Why not just something like list or getList?

👋 the platform team mainly pushed for using a prefix because it's a naming collision otherwise. we would have preferred userCollections but I think we all came to agreement on shareableList to disambiguate from the `list` that already exists in our legacy infrastructure and services (e.g. `list-api`).

2023-02-22 21:33 UTC, kschelonka commented on schema-public.graphql
> +  publicShareableList(slug: String!, userId: Float!): ShareableList
no comment on the public/private part, but that's where `shareable` came in

2023-02-23 16:54 UTC, jpetto commented on schema-public.graphql
> +  publicShareableList(slug: String!, userId: Float!): ShareableList
i could see us changing to `shareableListPublic` to keep the namespace front and center, but otherwise agree with kat on why "shareable" is included here.

2023-02-23 16:57 UTC, jpetto commented on schema-public.graphql
> +  publicShareableList(slug: String!, userId: Float!): ShareableList
as to your original question @nina-py - yes, the `userId` for this query will come in via params and _not_ through headers.

but there is a coordination here with the frontend team. at some point the username and slug need to be extracted from the URL - and i'm not sure which team should be responsible for that. i think having the web team responsible here makes the most sense, as otherwise we would receive a single param like `@username/list/some-slug-with-chars-123abc`. let's check with aly and anthony in slack.

2023-02-23 17:03 UTC, jpetto commented on src/database/queries/ShareableList.ts
> +  const storedSlug = matches[0];
agree - this does feel clunky and error prone. i don't think we have to block this PR as this will work, but i do think we should do a quick-ish re-assessment of slugs and the intentions of the constraints. (i'm not going to derail this PR by going into the history here 🙃.) but i will say that my reactionary stance is to drop the random digit/characters at the end of the slug.

2023-02-23 17:43 UTC, jpetto commented on src/database/queries/ShareableList.ts
> +  const storedSlug = matches[0];
i posted a [thread in slack](https://pocket.slack.com/archives/C04HWMUKLN5/p1677172037732649) suggesting we remove the ending characters as they aren't serving a functional purpose. we're waiting on priya (who is out this week but is sporadically checking slack) to confirm, but for now i'm of the opinion we drop the requirement.

2023-02-23 18:10 UTC, jpetto requested changes
a small PR with big discussions 😄. let me know if you need any further direction here (as i know a lot is going on), but i think all we are waiting for is a response from the web team on what params they can easily send.

2023-02-23 18:10 UTC, jpetto commented on schema-public.graphql
> +  publicShareableList(slug: String!, userId: Float!): ShareableList
[i have posed the question in slack](https://pocket.slack.com/archives/C04HWMUKLN5/p1677175331024949) in regards to what parameters are feasible/desirable to pass from the web team.

2023-02-28 10:40 UTC, nina-py reviewed
Closing in favour of starting afresh on a new branch as 47 commits to merge from main have proved to be a bit of a nightmare.

2023-02-28 10:40 UTC, closed without merging