feat(queries): [OSL-147, OSL-149] Set up a `shareableListPublic` query
Pocket/shareable-lists-api pull request #73
Opened 2023-03-01 08:51 UTC by nina-py

## Goal

Set up a query for publicly available lists. 

- Moved the basic resolver scaffolding from the [closed PR](https://github.com/Pocket/shareable-lists-api/pull/54).

- Added a 403 error for lists that have been taken down.

- Updated `userId` resolver to point to `PrismaBigInt` field resolver as it does on the admin schema.

## Tickets

- https://getpocket.atlassian.net/browse/OSL-147
- https://getpocket.atlassian.net/browse/OSL-149

2023-03-03 18:31 UTC, efixler commented on src/public/resolvers/queries/ShareableList.integration.ts
> +            userId: Number(list.userId),
@nina-py : This change (and the similar one below line 245) are what made the tests pass. (I had a little time and I was both curious and wanted to return the favor of merging my last PR : ) 

Not sure if you want to keep if this way, but the tests pass now.

2023-03-06 02:35 UTC, nina-py commented on src/public/resolvers/queries/ShareableList.integration.ts
> +            userId: Number(list.userId),
Yay! Thank you @efixler!

2023-03-06 17:21 UTC, jpetto requested changes
one (more) change on query inputs based on slack convos - at least the code gets simpler! and one question on `userId` validation.

2023-03-06 17:21 UTC, jpetto commented on schema-public.graphql
> +  shareableListPublic(slug: String!, userId: Float!): ShareableList
based on slack conversations and the current unreliability of `username`, we're going to fall back to just accepting the list's `externalId`. urls get uglier, but code is simpler!

2023-03-06 17:21 UTC, jpetto commented on src/public/resolvers/utils.ts
> +  return userId instanceof Array ? parseInt(userId[0]) : parseInt(userId);
is there any reason not to keep this line of code in `context.ts`? seems this could just be checked once at request time...

2023-03-06 22:36 UTC, nina-py commented on schema-public.graphql
> +  shareableListPublic(slug: String!, userId: Float!): ShareableList
Hooray! I think this is what this long-suffering PR started with :)

2023-03-06 22:36 UTC, nina-py commented on src/public/resolvers/utils.ts
> +  return userId instanceof Array ? parseInt(userId[0]) : parseInt(userId);
Good point, moving it back to public context!

2023-03-06 22:55 UTC, jpetto approved these changes
🚀

2023-03-06 22:59 UTC, merged