OSL-145: Emit snowplow events  to shared event-bridge
Pocket/shareable-lists-api pull request #82
Opened 2023-03-03 00:03 UTC by katerinachinnappan

## Goal

Emit snowplow events from shareable lists api to shared event-bridge.

* Added `src/snowplow` directory to hold logic for emitting snowplow events.
* Updated README on Snowplow
* Updated CircleCI config to run unit tests 
* Updated mutations to send the payload to the event-bridge.
* Installed `sinon` JS lib for stubbing AWS EventClientBridge in tests.

## Todos

- [x] deploy to dev

## Tickets

- [https://getpocket.atlassian.net/browse/OSL-145](https://getpocket.atlassian.net/browse/OSL-145
)

2023-03-03 00:25 UTC, nina-py reviewed
A few questions but otherwise solid effort! ⭐

2023-03-03 00:25 UTC, nina-py commented on .circleci/config.yml
> +          name: test_specs
We have a GitHub action to run unit tests, does it not encompass these new tests?

2023-03-03 00:25 UTC, nina-py commented on README.md
> +- `shareable-list-hidden`
I would send people off to check the schema in Snowplow and/or the spec repository. Keeping another copy of it in the docs in sync with everything else will be hard going forward.

2023-03-03 00:25 UTC, nina-py commented on src/database/mutations/ShareableList.ts
> +  }
Are we sending the update event regardless of sending the publish/unpublish event? The frontend will probably have three different buttons for it so it's not an issue but there's potential here to send publish+update or unpublish+update events

2023-03-03 00:25 UTC, nina-py commented on src/database/mutations/ShareableListItem.ts
>    });
This function is typed to return a promise, should it be updated after this change? Or will that work fine as is?

2023-03-03 00:30 UTC, sri-kirsh commented on src/snowplow/types.ts
> +export type SnowplowShareableList = {
probably at this point, we only have snowplow as the consumer for the events

but in-general we don't tie event emission to a consumer and emit as much domain related events and whatever format make sense for the microservice

and if the consumer wants it it in a specific format, then the consuming repo can do the ETL e.g [here](https://github.com/Pocket/shared-snowplow-consumer/blob/main/src/eventConsumer/userEvents/userEventConsumer.ts#L42)

 this is specifically useful if we see multiple consumers in the future (e.g another microservice as a consumer)

2023-03-03 00:35 UTC, sri-kirsh commented on README.md
> +- `shareable-list-hidden`
nice idea documenting the models. 

+1 on deciding if it should live in consumption repo as its consumer specific.. emitters can document its domain/business events

2023-03-03 02:32 UTC, katerinachinnappan commented on src/snowplow/types.ts
> +export type SnowplowShareableList = {
@sri-kirsh good point! I did tho intend the `snowplow` directory to be targeted for only snowplow events, hence I did the transformation in the repo.

2023-03-03 02:32 UTC, katerinachinnappan commented on src/database/mutations/ShareableListItem.ts
>    });
@nina-py it seems to work fine!

2023-03-03 02:33 UTC, katerinachinnappan commented on README.md
> +- `shareable-list-hidden`
good point, I will just refer to the schema definition in the spec repository.

2023-03-03 02:36 UTC, katerinachinnappan commented on src/database/mutations/ShareableList.ts
> +  }
@nina-py good catch. do we want to only send `shareable-list-updated` events for only title/description updates?

2023-03-03 18:35 UTC, katerinachinnappan commented on .circleci/config.yml
> +          name: test_specs
@nina-py I think that is only for main branch ? This runs tests on other branches, i don't have a preference if we should keep it

2023-03-03 18:38 UTC, katerinachinnappan commented on src/database/mutations/ShareableList.ts
> +  }
Updated the condition to check only for list title or description updates.

2023-03-03 21:52 UTC, jpetto requested changes
a few areas to address, but this is a really good start!

2023-03-03 21:52 UTC, jpetto commented on src/database/mutations/ShareableListItem.ts
>    });
afaik `async` functions _always_ return a promise.

2023-03-03 21:52 UTC, jpetto commented on src/database/mutations/ShareableListItem.ts
> +  });
do we need to `await` these calls? would be nice if we didn't have to block clients waiting for the event bridge call. i think we can _not_ await and it'll complete in the node event loop? maybe?

2023-03-03 21:52 UTC, jpetto commented on src/database/mutations/ShareableList.ts
> +  }
as this is a fair amount of event code, what do you think about factoring this out into its own function?

2023-03-03 21:52 UTC, jpetto commented on src/database/mutations/ShareableList.ts
> +  if (data.status === ListStatus.PUBLIC) {
something to watch out for here - the web client _may_ pass in the current value of any property. so i think we need to first check if `data.status !== list.status`.

2023-03-03 23:44 UTC, katerinachinnappan commented on src/database/mutations/ShareableListItem.ts
> +  });
i think if we don't use `await` it won't resolve into the `shareableListComplete` type?

2023-03-06 16:51 UTC, jpetto commented on src/database/mutations/ShareableListItem.ts
> +  });
apologies for the ambiguity! i meant the `sendEvent` calls specifically. i think we could let those calls complete on their own time and not block returning of data to the client.

2023-03-06 22:06 UTC, jpetto requested changes
a few more small tweaks, but it's very close 😄

2023-03-06 22:06 UTC, jpetto commented on src/database/mutations/ShareableList.ts
> +  }
nit pick - this could be simplified a little bit by first checking if `data.status !== list.status`, then in an inner `if/else if` check the status change (as only one status can be true per request).

basically, as it stands now, if the first `if` condition is met, attempting to run the second `if` condition is just using cpu cycles for no reason 😄

2023-03-06 22:06 UTC, jpetto commented on src/database/mutations/ShareableList.ts
> +    !data.status
i think it would be good to check web-client patterns here. the _might_ send all data here, even if it hasn't changed, meaning the `!data.status` check above could be faulty. what is the intent of the `!data.status` check? is there a reason not to send the `SHAREABLE_LIST_UPDATED` event if all three properties (`title`, `description`, and `status`) are present in `data`?

2023-03-06 22:06 UTC, jpetto commented on src/database/mutations/ShareableList.ts
> +function sendEventHelper(
just because there's another `sendEventHelper` defined in another file, maybe rename this to be more specific? maybe like `updateShareableListSendEventHelper`? then you wouldn't have to rename the import from `snowplow`.

2023-03-07 19:40 UTC, jpetto requested changes
a _tiny_ bit more cleanup 😄

2023-03-07 19:40 UTC, jpetto commented on src/public/resolvers/mutations/ShareableList.integration.ts
> +  let s3Stub: sinon.SinonStub;
nit - this variable name (also in the other `integration.ts` file) is a bit misleading, as we aren't stubbing `S3` 😉

2023-03-07 19:40 UTC, jpetto commented on src/snowplow/events.ts
> +async function transformAPIShareableListToSnowplowShareableList(
do these transformation functions need to be `async`?

2023-03-07 19:40 UTC, jpetto commented on src/snowplow/events.ts
> +export async function generateShareableListEventBridgePayload(
same question - do these generate functions need to be `async`?

2023-03-07 20:36 UTC, katerinachinnappan commented on src/public/resolvers/mutations/ShareableList.integration.ts
> +  let s3Stub: sinon.SinonStub;
good catch, i took this from my test in reparser 😅

2023-03-07 20:36 UTC, jpetto approved these changes
yay! ship it!

2023-03-07 20:40 UTC, merged